### ISSUE TITLE
Clarify in the user guide that the schema mapping definition must be uploaded

### ISSUE THREAD

**Issue by jakobbraun** [exasol/s3-document-files-virtual-schema#13]
Just like in the hands on guide

**Comment by pj-spoelders** [comment]
This is an old ticket, the edml documentation was moved to https://github.com/exasol/virtual-schema-common-document/main/doc/user_guide/edml_user_guide.md
I will close it here and open a new ticket in that repository to improve the documentation there:
https://github.com/exasol/virtual-schema-common-document/issues/142
