### ISSUE TITLE
Min.io guide

### ISSUE THREAD

**Issue by allipatev** [exasol/s3-document-files-virtual-schema#132]
There is a couple of possible inconsistencies in hands on guide for MinIO:

- It features two abbreviations "VSS3" and "S3VS". What do they mean and do we really need both?
- Variables `$MUSER`, `MPASS`, `$MHOST`, `$MBUCKET` are mentioned but not defined. Forgot to rename all occurrences?

**Comment by ckunki** [comment]
Thanks @allipatev I will fix this. 

* Correct abbreviation is VSS3, see file [error_code_config.yml](https://github.com/exasol/s3-document-files-virtual-schema/blob/main/error_code_config.yml)
* Variables should be named `$MINIO_HOST`, `$MINIO_USER`, `$MINIO_PASS`, `$MINIO_BUCKET`.
