### ISSUE TITLE
Hardcoded BucketFS path in User Guide

### ISSUE THREAD

**Issue by allipatev** [exasol/s3-document-files-virtual-schema#147]
User Guide for this VS (and for many others) hardcodes both BucketFS Service name and Bucket name in adapter, helper UDF function and mapping path:

```
 %jar /buckets/bfsdefault/default/...;
```

Not all users have extensive experience with Exasol github projects to not fall into this trap.

Please consider using placeholders for BucketFS Service name and Bucket name.

**Comment by redcatbear** [comment]
While certainly an improvement, we are not going to update 20 repos for this.
