### ISSUE TITLE
Is removal of SQL_DIALECT property also planned for this Virtual schema?

### ISSUE THREAD

**Issue by allipatev** [exasol/s3-document-files-virtual-schema#55]

**Comment by jakobbraun** [comment]
Yes. It's no longer required. 
I created a ticket for removing it from the doc:
https://github.com/exasol/s3-document-files-virtual-schema/issues/new

**Comment by jakobbraun** [comment]
However, there is no need to remove it. You can still specify it.
Can we close this ticket?

**Comment by allipatev** [comment]
Thanks, @jakobbraun.
Yes, the ticket can be closed.
