### ISSUE TITLE
Can we query files in private S3 "custom endpoints" without dns style bucket level access

### ISSUE THREAD

**Issue by berndlunghamer** [exasol/s3-document-files-virtual-schema#59]
Currently when we query an internal S3 compatible store such as minio, we get bucket string exceptions. The syntax does not allow for custom endpoints with path style access and without s3 in the bucket string. Thus we cannot use this with custom internal endpoints. Is there any means to enable path style access (bucket is not visible in dns but is first url part after domain name) or relax the requirement on the url format:

Exception / Stacktrace from query: SELECT * FROM FILES_VS_TEST."metrics" LIMIT 10

SQL-Error [22002]: VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026: 
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall 
java.lang.IllegalArgumentException: E-S3VS-1: The given S3 Bucket string 'https://<private_endpoint>/test/metrics' has an invalid format. Expected format: http(s)://BUCKET.s3.REGION.amazonaws.com/KEY or http(s)://BUCKET.s3.REGION.CUSTOM_ENDPOINT/KEY. Note that the address from the CONNECTION and the source are concatenated. Change the address in your CONNECTION and the source in your mapping definition.
com.exasol.adapter.document.files.S3Uri.fromString(S3Uri.java:58)
com.exasol.adapter.document.files.S3FileLoader.<init>(S3FileLoader.java:37)
com.exasol.adapter.document.files.S3FileLoaderFactory.getLoader(S3FileLoaderFactory.java:15)
com.exasol.adapter.document.files.FilesDocumentFetcherFactory.buildSegmentDescriptions(FilesDocumentFetcherFactory.java:59)
com.exasol.adapter.document.files.FilesDocumentFetcherFactory.buildDocumentFetcherForQuery(FilesDocumentFetcherFactory.java:39)
com.exasol.adapter.document.files.FilesQueryPlanner.planQuery(FilesQueryPlanner.java:33)
com.exasol.adapter.document.DocumentAdapter.runQuery(DocumentAdapter.java:122)
com.exasol.adapter.document.DocumentAdapter.pushdown(DocumentAdapter.java:107)
com.exasol.adapter.AdapterCallExecutor.executePushDownRequest(AdapterCallExecutor.java:109)
com.exasol.adapter.request.PushDownRequest.executeWith(PushDownRequest.java:55)
com.exasol.adapter.AdapterCallExecutor.executeAdapterCall(AdapterCallExecutor.java:26)
com.exasol.adapter.RequestDispatcher.processAdapterCall(RequestDispatcher.java:48)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:33)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:100)
 (Session: 1718395300191535104)

**Comment by jakobbraun** [comment]
Hi,
Please notice that path style syntax is deprecated: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html

However, you use case seems reasonable and can also apply for other customers. So we will try to integrate this syntax into this virtual-schema. You can expect a new release in the next weeks. 

But, if the AWS SDK for Java v2 stops supporting the path style syntax, we will also  have to stop the support.

**Comment by berndlunghamer** [comment]
Hi Jakob, thanks for the reply and that your are looking into it. 

Yes path style has been deprecated. One option could be to directly interface with minio java sdk (https://docs.min.io/docs/java-client-api-reference.html) which is more lightweight than aws S3 SDK and will probably support path style access longer (due to on prem dns challenges)

**Comment by jakobbraun** [comment]
That sound also like a great idea. However, for us, it's currently not on the roadmap. But you could simply fork this repo and replace the client. In case that works for you please let me know. Otherwise, I'll add the option for the AWS client.
