### ISSUE TITLE
Support dots in bucket name

### ISSUE THREAD

**Issue by jakobbraun** [exasol/s3-document-files-virtual-schema#62]
According to the [AWS S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html), AWS S3 supports dots in bucket names. Currently, that does not work with the S3 Virtual Schema.

**Comment by pj-spoelders** [comment]
Needs to be revisited/checked if still relevant after planned changes to virtual schemas.

**Comment by jakobbraun** [comment]
this will be solved by #64
